#!/bin/sh
#
# Copyright (C) 2014 Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

if [ -f /var/openstack/horizon-setup ]; then
  exit 0
fi

# Create required system users and groups
getent group horizon >/dev/null || groupadd -r --gid 167 horizon
getent passwd neutron >/dev/null || \
	useradd --uid 167 -r -g horizon -d /var/lib/horizon -s /sbin/nologin \
	-c "Horizon user" horizon

chown -R horizon:horizon /var/lib/horizon

# Link horizon configuration file for apache to the directory where our apache load
# configurations files
ln -sf /etc/horizon/apache-horizon.conf /etc/httpd/conf.d/apache-horizon.conf

install -D -m 644 /proc/self/fd/0 <<'EOF' /var/openstack/horizon-setup
Horizon setup: success
EOF

exit 0
